PET FERA: Animal.cpp File Reference
Animal.cpp File Reference
#include "../includes/Animal.h"
Functions
istream & operator>> (istream &is, Animal &animal)
Function Documentation
operator>>()
istream& operator>> (istream & is, Animal & animal)
Definition at line 102 of file Animal.cpp.
References Animal::m_classe, Animal::m_dieta, Animal::m_nome, Animal::m_nome_batismo, Animal::m_nome_cientifico, Animal::setM_id(), Animal::setM_sexo(), and Animal::setM_tamanho().
{
         /*string id;
   getline(is, id, ';');
         getline(is, animal.m_classe, ';');
         is>>animal.m_nome_cientifico;
         animal.setM_id(stoi(id));*/
         string id, tamanho, sexo;
   getline(is, id, ';');
         getline(is, animal.m_classe, ';');
         getline(is, animal.m_nome, ';');
         getline(is, animal.m_nome_cientifico, ';');
         getline(is, sexo, ';');
         animal.setM_sexo(sexo[0]);
         getline(is, tamanho, ';');
         getline(is, animal.m_dieta, ';');
         //getline(is, animal.m_nome_batismo,';');
         //getline(is, id_veterinario, ';');
         getline(is,animal.m_nome_batismo,';');
         try{
         if(!id.empty()) animal.setM_id(stoi(id));
         if(!tamanho.empty()) animal.setM_tamanho(stod(tamanho));
         }catch (const std::exception &e)
     {
       cout << "Id inválido ou existente" << endl;
     }
         /*is >> animal.m_id;
                 //>> delim
         is.ignore(2,';');
         is>> animal.m_classe;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_nome_cientifico;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_sexo;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_tamanho;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_dieta;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_nome_batismo;*/
   return is;
 }