PET FERA: SistemaAnimal Class Reference
SistemaAnimal Class Reference
#include "SistemaAnimal.h"
Public Member Functions
SistemaAnimal ()
~SistemaAnimal ()
void carregarDados ()
void cadastrarAnimal ()
void salvarAlteracao ()
void alterarDados (int id, Animal a)
void listarAnimais ()
void consultar_animal_por_classe (string classe)
void consultar_animal_por_tratador (int id_tratador)
void consultar_animal_por_veterinario (int id_veterinario)
Veterinario getVeterinario_por_id (int id)
Tratador getTratador_por_id (int id)
SistemaAnimal ()
~SistemaAnimal ()
void carregarDados ()
void cadastrarAnimal ()
void salvarAlteracao ()
void alterarDados (int id)
void deletarAnimal (int id)
void listarAnimal ()
void consultar_animal_por_classe (string classe)
void consultar_animal_por_tratador (int id_tratador)
void consultar_animal_por_veterinario (int id_veterinario)
Veterinario getVeterinario_por_id (int id)
Tratador getTratador_por_id (int id)
Private Attributes
map< int, Animal > animais
map< int, Veterinario > veterinarios
map< int, Tratador > tratadores
Detailed Description
Definition at line 26 of file includes/SistemaAnimal.h.
Constructor & Destructor Documentation
SistemaAnimal() [1/2]
SistemaAnimal::SistemaAnimal ()
Definition at line 244 of file SistemaAnimal.cpp.
References carregarDados().
 {
     carregarDados();
 }
~SistemaAnimal() [1/2]
SistemaAnimal::~SistemaAnimal ()
Definition at line 248 of file SistemaAnimal.cpp.
 {
 }
SistemaAnimal() [2/2]
SistemaAnimal::SistemaAnimal ()
~SistemaAnimal() [2/2]
SistemaAnimal::~SistemaAnimal ()
Member Function Documentation
alterarDados() [1/2]
void SistemaAnimal::alterarDados (int id)
Definition at line 173 of file SistemaAnimal.cpp.
References animais, getTratador_por_id(), getVeterinario_por_id(), salvarAlteracao(), tratadores, and veterinarios.
{
     //TO DO
     auto a=animais.find(id);
     if(a!=animais.end()){
         string respostas = "-1";
         double tamanho;
         cout<<"Digite a classe:"<<endl;
         getline(cin, respostas);
         a->second.setM_classe(respostas);
         cout<<"Digite o nome:"<<endl;
         getline(cin, respostas);
         a->second.setM_nome(respostas);
         cout<<"Digite o nome cientifico:"<<endl;
         getline(cin, respostas);
         a->second.setM_nome_cientifico(respostas);
         cout<<"Digite o sexo (F ou M):"<<endl;
         getline(cin, respostas);
         a->second.setM_sexo(respostas[0]);
         cout<<"Digite o tamanho:"<<endl;
         getline(cin, respostas);
         tamanho=stod(respostas);
         a->second.setM_tamanho(tamanho);
         cout<<"Digite a dieta:"<<endl;
         getline(cin, respostas);
         a->second.setM_dieta(respostas);
         cout<<"Digite o nome de batismo:"<<endl;
         getline(cin, respostas);
         a->second.setM_nome_batismo(respostas);
         int id_veterinario;
         do{
             cout<<"Digite o id do veterinário (0 caso não exista):"<<endl;
             cin>>id_veterinario;
             if(id_veterinario<=0) break;
             if(veterinarios.find(id_veterinario)!=veterinarios.end()){
                 a->second.setM_veterinario(getVeterinario_por_id(id_veterinario));
             }else{
                 cout<<"ID de veterinário inválido"<<endl;
             }
         }while(veterinarios.find(id_veterinario)==veterinarios.end());
         int id_tratador;
         do{
             cout<<"Digite o id do tratador (0 caso não exista):"<<endl;
             cin>>id_tratador;
             if(id_tratador<=0) break;
             if(tratadores.find(id_tratador)!=tratadores.end()){
                 a->second.setM_tratador(getTratador_por_id(id_tratador));
             }else{
                 cout<<"ID de tratador inválido"<<endl;
             }
         }while(tratadores.find(id_tratador)==tratadores.end());
     }else{
         cout<<"Animal não encontrado"<<endl;
     }
     salvarAlteracao();
 }
alterarDados() [2/2]
void SistemaAnimal::alterarDados (int id, Animal a)
cadastrarAnimal() [1/2]
void SistemaAnimal::cadastrarAnimal ()
cadastrarAnimal() [2/2]
void SistemaAnimal::cadastrarAnimal ()
Definition at line 97 of file SistemaAnimal.cpp.
References animais, getTratador_por_id(), getVeterinario_por_id(), salvarAlteracao(), Animal::setM_classe(), Animal::setM_dieta(), Animal::setM_id(), Animal::setM_nome(), Animal::setM_nome_batismo(), Animal::setM_nome_cientifico(), Animal::setM_sexo(), Animal::setM_tamanho(), Animal::setM_tratador(), Animal::setM_veterinario(), tratadores, and veterinarios.
{
         Animal *a = new Animal();
         int maior_id=(animais.rbegin()->first)+1;
     a->setM_id(maior_id);
         string respostas = "-1";
         double tamanho;
         cout<<"Digite a classe:"<<endl;
         getline(cin, respostas);
         a->setM_classe(respostas);
         cout<<"Digite o nome:"<<endl;
         getline(cin, respostas);
         a->setM_nome(respostas);
         cout<<"Digite o nome cientifico:"<<endl;
         getline(cin, respostas);
         a->setM_nome_cientifico(respostas);
         cout<<"Digite o sexo (F ou M):"<<endl;
         getline(cin, respostas);
         a->setM_sexo(respostas[0]);
         cout<<"Digite o tamanho:"<<endl;
         getline(cin, respostas);
     tamanho=stod(respostas);
         a->setM_tamanho(tamanho);
     cout<<"Digite a dieta:"<<endl;
         getline(cin, respostas);
         a->setM_dieta(respostas);
         cout<<"Digite o nome de batismo:"<<endl;
         getline(cin, respostas);
         a->setM_nome_batismo(respostas);
         int id_veterinario;
     do{
         cout<<"Digite o id do veterinário (0 caso não exista):"<<endl;
         cin>>id_veterinario;
         if(id_veterinario<=0) break;
         if(veterinarios.find(id_veterinario)!=veterinarios.end()){
             a->setM_veterinario(getVeterinario_por_id(id_veterinario));
         }else{
             cout<<"ID de veterinário inválido"<<endl;
         }
     }while(veterinarios.find(id_veterinario)==veterinarios.end());
         int id_tratador;
     do{
         cout<<"Digite o id do tratador (0 caso não exista):"<<endl;
         cin>>id_tratador;
         if(id_tratador<=0) break;
         if(id_tratador>0 && tratadores.find(id_tratador)!=tratadores.end()){
             a->setM_tratador(getTratador_por_id(id_tratador));
         }else{
             cout<<"ID de tratador inválido"<<endl;
         }
     }while(tratadores.find(id_tratador)==tratadores.end());
     animais.insert(pair<int, Animal>(maior_id, *a));
     salvarAlteracao();
 }
carregarDados() [1/2]
void SistemaAnimal::carregarDados ()
carregarDados() [2/2]
includes SistemaAnimal h void SistemaAnimal::carregarDados ()
Definition at line 2 of file SistemaAnimal.cpp.
References animais, Funcionario::getM_id(), getTratador_por_id(), getVeterinario_por_id(), Funcionario::setM_cpf(), Veterinario::setM_crmv(), Funcionario::setM_especialidade(), Funcionario::setM_fator_rh(), Funcionario::setM_id(), Funcionario::setM_idade(), Funcionario::setM_nome(), Funcionario::setM_tipo_sanguineo(), Tratador::SetNivel_de_seguranca(), tratadores, and veterinarios.
Referenced by SistemaAnimal().
{
         /*for (auto e:animais){
                 cout<<e.first<<"\t"<<e.second.getM_nome()<<endl;
         }*/
         //carregando os dados cadastrados de funcionarios
     ifstream arquivoFuncionario("./funcionarios.csv");
         string linha;
         while (getline(arquivoFuncionario, linha)) {
       stringstream linestream(linha);
                         string tipoFuncionario, id;
                         getline(linestream, id, ';');
                         getline(linestream, tipoFuncionario, ';');
                         //cout<<tipoFuncionario<<endl;
                         string nome, cpf, idade, tipo_sanguineo, fator_rh, especialidade, vazio;
                         getline(linestream, nome, ';');
                         getline(linestream, cpf, ';');
                         getline(linestream, idade, ';');
                         getline(linestream, tipo_sanguineo, ';');
                         getline(linestream, fator_rh, ';');
                         getline(linestream, especialidade, ';');
                         if(tipoFuncionario=="Veterinario") {
                                 string crmv;
                                 getline(linestream, crmv, ';');
                                 linestream>>vazio;
                                 Veterinario v;
                                 v.setM_id(stoi(id));
                                 v.setM_nome(nome);
                                 v.setM_cpf(cpf);
                                 v.setM_idade(stoi(idade));
                                 v.setM_tipo_sanguineo(tipo_sanguineo);
                                 v.setM_fator_rh(fator_rh[0]);
                                 v.setM_especialidade(especialidade);
                                 v.setM_crmv(crmv);
                                 veterinarios.insert(pair<int, Veterinario>(v.getM_id(), v));
                         }else if(tipoFuncionario=="Tratador"){
                                 int seguranca;
                                 getline(linestream, vazio, ';');
                                 linestream>>seguranca;
                                 Tratador t;
                                 t.setM_id(stoi(id));
                                 t.setM_nome(nome);
                                 t.setM_cpf(cpf);
                                 t.setM_idade(stoi(idade));
                                 t.setM_tipo_sanguineo(tipo_sanguineo);
                                 t.setM_fator_rh(fator_rh[0]);
                                 t.setM_especialidade(especialidade);
                                 t.SetNivel_de_seguranca(seguranca);
                                 tratadores.insert(pair<int, Tratador>(t.getM_id(), t));
                         }
         }
         arquivoFuncionario.close();
         //carregando os dados cadastrados de animais
   ifstream arquivoAnimal;
   arquivoAnimal.open ("./src/animais.csv");
         string line;
   if (!arquivoAnimal)
     cout<<"não tem arquivo"<<endl;
         while (getline(arquivoAnimal, line)) {
                         Animal dados;
       stringstream lineAnimal (line);
       lineAnimal >> dados;
                         string id_veterinario, id_tratador;
                         getline(lineAnimal, id_veterinario, ';');
                         lineAnimal>>id_tratador;
                         if(!id_veterinario.empty() && id_veterinario!="0"){
                                 dados.setM_veterinario(getVeterinario_por_id(stoi(id_veterinario)));
                         }
                         if(!id_tratador.empty() && id_tratador!="0"){
                                 dados.setM_tratador(getTratador_por_id(stoi(id_tratador)));
                         }
                         animais.insert(pair<int, Animal>(dados.getM_id(), dados));
         }
         arquivoAnimal.close();
         /*cout<<"Animais:"<<endl;
         for (auto e:animais){
                 Veterinario v = e.second.getM_veterinario();
                 Tratador t = e.second.getM_tratador();
                 cout<<e.first<<"\t Veterinario:"<<v.getM_nome()<<"\t Tratador:"<<t.getM_nome()<<endl;
         }
         cout<<"Veterinarios:"<<endl;
         for (auto e:veterinarios){
                 cout<<e.first<<"\t"<<e.second.getM_nome()<<endl;
         }
         cout<<"Tratadores:"<<endl;
         for (auto e:tratadores){
                 cout<<e.first<<"\t"<<e.second.getM_nome()<<endl;
         } */
 }
consultar_animal_por_classe() [1/2]
void SistemaAnimal::consultar_animal_por_classe (string classe)
consultar_animal_por_classe() [2/2]
void SistemaAnimal::consultar_animal_por_classe (string classe)
Definition at line 235 of file SistemaAnimal.cpp.
{
     //TO DO
 }
consultar_animal_por_tratador() [1/2]
void SistemaAnimal::consultar_animal_por_tratador (int id_tratador)
consultar_animal_por_tratador() [2/2]
void SistemaAnimal::consultar_animal_por_tratador (int id_tratador)
Definition at line 238 of file SistemaAnimal.cpp.
{
     //TO DO
 }
consultar_animal_por_veterinario() [1/2]
void SistemaAnimal::consultar_animal_por_veterinario (int id_veterinario)
Definition at line 241 of file SistemaAnimal.cpp.
{
     //TO DO
 }
consultar_animal_por_veterinario() [2/2]
void SistemaAnimal::consultar_animal_por_veterinario (int id_veterinario)
deletarAnimal()
void SistemaAnimal::deletarAnimal (int id)
Definition at line 228 of file SistemaAnimal.cpp.
References animais, and salvarAlteracao().
{
     animais.erase(id);
     salvarAlteracao();
 }
getTratador_por_id() [1/2]
Tratador SistemaAnimal::getTratador_por_id (int id)
Definition at line 94 of file SistemaAnimal.cpp.
References tratadores.
Referenced by alterarDados(), cadastrarAnimal(), and carregarDados().
{
         return tratadores.find(id)->second;
 }
getTratador_por_id() [2/2]
Tratador SistemaAnimal::getTratador_por_id (int id)
getVeterinario_por_id() [1/2]
Veterinario SistemaAnimal::getVeterinario_por_id (int id)
getVeterinario_por_id() [2/2]
Veterinario SistemaAnimal::getVeterinario_por_id (int id)
Definition at line 91 of file SistemaAnimal.cpp.
References veterinarios.
Referenced by alterarDados(), cadastrarAnimal(), and carregarDados().
{
         return veterinarios.find(id)->second;
 }
listarAnimais()
void SistemaAnimal::listarAnimais ()
listarAnimal()
void SistemaAnimal::listarAnimal ()
Definition at line 232 of file SistemaAnimal.cpp.
{
     //TO DO
 }
salvarAlteracao() [1/2]
void SistemaAnimal::salvarAlteracao ()
salvarAlteracao() [2/2]
void SistemaAnimal::salvarAlteracao ()
Definition at line 151 of file SistemaAnimal.cpp.
References animais, Funcionario::getM_id(), and Funcionario::getM_nome().
Referenced by alterarDados(), cadastrarAnimal(), and deletarAnimal().
{
     ofstream arquivo;
     arquivo.open ("./src/animais.csv");
     if (!arquivo) cout<<"não tem arquivo"<<endl;
         for (auto e:animais){
                 arquivo<<e.first<<";"<<e.second.getM_classe()<<";"<<e.second.getM_nome()<<";"<<e.second.getM_nome_cientifico()<<";"<<e.second.getM_sexo()<<";"<<e.second.getM_tamanho()<<";"<<e.second.getM_dieta()<<";"<<e.second.getM_nome_batismo();
         Veterinario v=e.second.getM_veterinario();
         Tratador t = e.second.getM_tratador();
         if(v.getM_nome()!=""){
             arquivo<<";"<<v.getM_id();
         }else{
             arquivo<<";"<<"0";
         }
         if(t.getM_nome()!=""){
             arquivo<<";"<<t.getM_id();
         }else{
             arquivo<<";"<<"0";
         }
         arquivo<<endl;
         }
         arquivo.close();
 }
Member Data Documentation
animais
map< int, Animal > SistemaAnimal::animais private
Definition at line 28 of file includes/SistemaAnimal.h.
Referenced by alterarDados(), cadastrarAnimal(), carregarDados(), deletarAnimal(), and salvarAlteracao().
tratadores
map< int, Tratador > SistemaAnimal::tratadores private
Definition at line 30 of file includes/SistemaAnimal.h.
Referenced by alterarDados(), cadastrarAnimal(), carregarDados(), and getTratador_por_id().
veterinarios
map< int, Veterinario > SistemaAnimal::veterinarios private
Definition at line 29 of file includes/SistemaAnimal.h.
Referenced by alterarDados(), cadastrarAnimal(), carregarDados(), and getVeterinario_por_id().
The documentation for this class was generated from the following files:
includes/SistemaAnimal.h
SistemaAnimal.cpp