PET FERA: Veterinario Class Reference
Veterinario Class Reference
#include "Veterinario.h"
Public Member Functions
string getM_crmv ()
void setM_crmv (string m_crmv)
Veterinario & operator= (Veterinario &v)
Public Member Functions inherited from Funcionario
Funcionario ()
~Funcionario ()
int getM_id ()
void setM_id (int m_id)
string getM_nome ()
void setM_nome (string m_nome)
string getM_cpf ()
void setM_cpf (string m_cpf)
short getM_idade ()
void setM_idade (short m_idade)
string getM_tipo_sanguineo ()
void setM_tipo_sanguineo (string m_tipo_sanguineo)
char getM_fator_rh ()
void setM_fator_rh (char m_fator_rh)
string getM_especialidade ()
void setM_especialidade (string m_especialidade)
void setM_funcao (string m_funcao)
string getM_funcao ()
Funcionario & operator= (const Funcionario &f)
Private Attributes
string m_crmv
Detailed Description
Definition at line 16 of file Veterinario.h.
Member Function Documentation
getM_crmv()
string Veterinario::getM_crmv ()
Definition at line 2 of file Veterinario.cpp.
References m_crmv.
Referenced by Sistema::cadastrar_Veterinario().
 {
     return this->m_crmv;
 }
operator=()
Veterinario & Veterinario::operator= (Veterinario & v)
Definition at line 12 of file Veterinario.cpp.
References Funcionario::getM_cpf(), Funcionario::getM_especialidade(), Funcionario::getM_fator_rh(), Funcionario::getM_id(), Funcionario::getM_idade(), Funcionario::getM_nome(), Funcionario::getM_tipo_sanguineo(), m_crmv, Funcionario::setM_cpf(), Funcionario::setM_especialidade(), Funcionario::setM_fator_rh(), Funcionario::setM_id(), Funcionario::setM_idade(), Funcionario::setM_nome(), and Funcionario::setM_tipo_sanguineo().
{
         this->setM_id(v.getM_id());
         this->setM_nome(v.getM_nome());
         this->setM_cpf(v.getM_cpf());
         this->setM_idade(v.getM_idade());
         this->setM_tipo_sanguineo(v.getM_tipo_sanguineo());
         this->setM_fator_rh(v.getM_fator_rh());
         this->setM_especialidade(v.getM_especialidade());
   m_crmv = v.m_crmv;
   return *this;
 }
setM_crmv()
void Veterinario::setM_crmv (string m_crmv)
Definition at line 6 of file Veterinario.cpp.
References m_crmv.
Referenced by Sistema::cadastrar_Veterinario(), and SistemaAnimal::carregarDados().
 {
     this->m_crmv = m_crmv;
 }
Member Data Documentation
m_crmv
string Veterinario::m_crmv private
Definition at line 18 of file Veterinario.h.
Referenced by getM_crmv(), operator=(), and setM_crmv().
The documentation for this class was generated from the following files:
Veterinario.h
Veterinario.cpp