PET FERA: Data Class Reference
Data Class Reference
#include "data.h"
Public Member Functions
Data ()
Data (int dia, int mes, int ano)
~Data ()
int getDia ()
void setDia (int dia)
int getMes ()
void setMes (int mes)
int getAno ()
void setAno (int ano)
Data & operator= (Data const &f)
Private Attributes
int dia
int mes
int ano
Friends
ostream & operator<< (ostream &o, Data const d)
Detailed Description
Definition at line 15 of file data.h.
Constructor & Destructor Documentation
Data() [1/2]
Data::Data ()
Definition at line 2 of file data.cpp.
           {
 }
Data() [2/2]
Data::Data (int dia, int mes, int ano)
Definition at line 5 of file data.cpp.
References ano, dia, and mes.
{
     this->dia = dia;
     this->mes = mes;
     this->ano = ano;
 };
~Data()
Data::~Data ()
Definition at line 25 of file data.cpp.
 {}
Member Function Documentation
getAno()
int Data::getAno () inline
Definition at line 38 of file data.h.
Referenced by checarDataValida(), dateToString(), and diferencaDatas().
                 {
         return this->ano;
     };
getDia()
int Data::getDia () inline
Definition at line 26 of file data.h.
Referenced by checarDataValida(), dateToString(), and diferencaDatas().
                 {
         return this->dia;
     };
getMes()
int Data::getMes () inline
Definition at line 32 of file data.h.
Referenced by checarDataValida(), dateToString(), and diferencaDatas().
                 {
         return this->mes;
     };
operator=()
Data & Data::operator= (Data const & f)
Definition at line 11 of file data.cpp.
References ano, dia, and mes.
{
     this->dia = d.dia;
     this->mes = d.mes;
     this->ano = d.ano;
     return *this;
 };
setAno()
void Data::setAno (int ano) inline
Definition at line 41 of file data.h.
References operator<<().
{
         this->ano = ano;
     };
setDia()
void Data::setDia (int dia) inline
Definition at line 29 of file data.h.
{
         this->dia = dia;
     }
setMes()
void Data::setMes (int mes) inline
Definition at line 35 of file data.h.
{
         this->mes = mes;
     }
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & o, Data const d) friend
Definition at line 19 of file data.cpp.
{
     o << d.dia << "/" << d.mes << "/" << d.ano;
     return o;
 };
Member Data Documentation
ano
int Data::ano private
Definition at line 19 of file data.h.
Referenced by Data(), operator<<(), and operator=().
dia
int Data::dia private
Definition at line 17 of file data.h.
Referenced by Data(), operator<<(), and operator=().
mes
int Data::mes private
Definition at line 18 of file data.h.
Referenced by Data(), operator<<(), and operator=().
The documentation for this class was generated from the following files:
data.h
data.cpp