PET FERA: Funcionario Class Reference
Funcionario Class Reference
#include "Funcionario.h"
Public Member Functions
Funcionario ()
~Funcionario ()
int getM_id ()
void setM_id (int m_id)
string getM_nome ()
void setM_nome (string m_nome)
string getM_cpf ()
void setM_cpf (string m_cpf)
short getM_idade ()
void setM_idade (short m_idade)
string getM_tipo_sanguineo ()
void setM_tipo_sanguineo (string m_tipo_sanguineo)
char getM_fator_rh ()
void setM_fator_rh (char m_fator_rh)
string getM_especialidade ()
void setM_especialidade (string m_especialidade)
void setM_funcao (string m_funcao)
string getM_funcao ()
Funcionario & operator= (const Funcionario &f)
Private Attributes
int m_id
string m_nome
string m_cpf
short m_idade
string m_tipo_sanguineo
char m_fator_rh
string m_especialidade
string m_funcao
Friends
ostream & operator<< (ostream &o, Funcionario const f)
Detailed Description
Definition at line 15 of file Funcionario.h.
Constructor & Destructor Documentation
Funcionario()
Funcionario::Funcionario ()
Definition at line 85 of file Funcionario.cpp.
{
 }
~Funcionario()
Funcionario::~Funcionario ()
Definition at line 88 of file Funcionario.cpp.
{
 }
Member Function Documentation
getM_cpf()
string Funcionario::getM_cpf ()
Definition at line 27 of file Funcionario.cpp.
References m_cpf.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), Veterinario::operator=(), and Tratador::operator=().
 {
     return this->m_cpf;
 }
getM_especialidade()
string Funcionario::getM_especialidade ()
Definition at line 75 of file Funcionario.cpp.
References m_especialidade.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), Veterinario::operator=(), and Tratador::operator=().
 {
     return this->m_especialidade;
 }
getM_fator_rh()
char Funcionario::getM_fator_rh ()
Definition at line 63 of file Funcionario.cpp.
References m_fator_rh.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), Veterinario::operator=(), and Tratador::operator=().
 {
     return this->m_fator_rh;
 }
getM_funcao()
string Funcionario::getM_funcao ()
Definition at line 94 of file Funcionario.cpp.
References m_funcao.
Referenced by Sistema::cadastrar_Tratador(), and Sistema::cadastrar_Veterinario().
{
   return this->m_funcao;
 }
getM_id()
int Funcionario::getM_id ()
Definition at line 3 of file Funcionario.cpp.
References m_id.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), SistemaAnimal::carregarDados(), Veterinario::operator=(), Tratador::operator=(), and SistemaAnimal::salvarAlteracao().
 {
     return this->m_id;
 }
getM_idade()
short Funcionario::getM_idade ()
Definition at line 39 of file Funcionario.cpp.
References m_idade.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), Veterinario::operator=(), and Tratador::operator=().
 {
     return this->m_idade;
 }
getM_nome()
string Funcionario::getM_nome ()
Definition at line 15 of file Funcionario.cpp.
References m_nome.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), Veterinario::operator=(), Tratador::operator=(), and SistemaAnimal::salvarAlteracao().
 {
     return this->m_nome;
 }
getM_tipo_sanguineo()
string Funcionario::getM_tipo_sanguineo ()
Definition at line 51 of file Funcionario.cpp.
References m_tipo_sanguineo.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), Veterinario::operator=(), and Tratador::operator=().
 {
     return this->m_tipo_sanguineo;
 }
operator=()
Funcionario & Funcionario::operator= (const Funcionario & f)
Definition at line 97 of file Funcionario.cpp.
References m_cpf, m_especialidade, m_fator_rh, m_id, m_idade, m_nome, and m_tipo_sanguineo.
{
         m_id=f.m_id;
         m_nome=f.m_nome;
         m_cpf=f.m_cpf;
         m_idade=f.m_idade;
         m_tipo_sanguineo=f.m_tipo_sanguineo;
         m_fator_rh=f.m_fator_rh;
         m_especialidade=f.m_especialidade;
         return *this;
 }
setM_cpf()
void Funcionario::setM_cpf (string m_cpf)
Definition at line 33 of file Funcionario.cpp.
References m_cpf.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), SistemaAnimal::carregarDados(), Veterinario::operator=(), and Tratador::operator=().
 {
     this->m_cpf = m_cpf;
 }
setM_especialidade()
void Funcionario::setM_especialidade (string m_especialidade)
Definition at line 81 of file Funcionario.cpp.
References m_especialidade.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), SistemaAnimal::carregarDados(), Veterinario::operator=(), and Tratador::operator=().
 {
     this->m_especialidade = m_especialidade;
 }
setM_fator_rh()
void Funcionario::setM_fator_rh (char m_fator_rh)
Definition at line 69 of file Funcionario.cpp.
References m_fator_rh.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), SistemaAnimal::carregarDados(), Veterinario::operator=(), and Tratador::operator=().
 {
     this->m_fator_rh = m_fator_rh;
 }
setM_funcao()
void Funcionario::setM_funcao (string m_funcao)
Definition at line 91 of file Funcionario.cpp.
References m_funcao.
Referenced by Sistema::cadastrar_Tratador(), and Sistema::cadastrar_Veterinario().
{
   this->m_funcao = m_funcao;
 }
setM_id()
void Funcionario::setM_id (int m_id)
Definition at line 9 of file Funcionario.cpp.
References m_id.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), SistemaAnimal::carregarDados(), Veterinario::operator=(), and Tratador::operator=().
 {
     this->m_id = m_id;
 }
setM_idade()
void Funcionario::setM_idade (short m_idade)
Definition at line 45 of file Funcionario.cpp.
References m_idade.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), SistemaAnimal::carregarDados(), Veterinario::operator=(), and Tratador::operator=().
 {
     this->m_idade = m_idade;
 }
setM_nome()
void Funcionario::setM_nome (string m_nome)
Definition at line 21 of file Funcionario.cpp.
References m_nome.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), SistemaAnimal::carregarDados(), Veterinario::operator=(), and Tratador::operator=().
 {
     this->m_nome = m_nome;
 }
setM_tipo_sanguineo()
void Funcionario::setM_tipo_sanguineo (string m_tipo_sanguineo)
Definition at line 57 of file Funcionario.cpp.
References m_tipo_sanguineo.
Referenced by Sistema::cadastrar_Tratador(), Sistema::cadastrar_Veterinario(), SistemaAnimal::carregarDados(), Veterinario::operator=(), and Tratador::operator=().
 {
     this->m_tipo_sanguineo = m_tipo_sanguineo;
 }
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & o, Funcionario const f) friend
Member Data Documentation
m_cpf
string Funcionario::m_cpf private
Definition at line 19 of file Funcionario.h.
Referenced by getM_cpf(), operator=(), and setM_cpf().
m_especialidade
string Funcionario::m_especialidade private
Definition at line 23 of file Funcionario.h.
Referenced by getM_especialidade(), operator=(), and setM_especialidade().
m_fator_rh
char Funcionario::m_fator_rh private
Definition at line 22 of file Funcionario.h.
Referenced by getM_fator_rh(), operator=(), and setM_fator_rh().
m_funcao
string Funcionario::m_funcao private
Definition at line 24 of file Funcionario.h.
Referenced by getM_funcao(), and setM_funcao().
m_id
int Funcionario::m_id private
Definition at line 17 of file Funcionario.h.
Referenced by getM_id(), operator=(), and setM_id().
m_idade
short Funcionario::m_idade private
Definition at line 20 of file Funcionario.h.
Referenced by getM_idade(), operator=(), and setM_idade().
m_nome
string Funcionario::m_nome private
Definition at line 18 of file Funcionario.h.
Referenced by getM_nome(), operator=(), and setM_nome().
m_tipo_sanguineo
string Funcionario::m_tipo_sanguineo private
Definition at line 21 of file Funcionario.h.
Referenced by getM_tipo_sanguineo(), operator=(), and setM_tipo_sanguineo().
The documentation for this class was generated from the following files:
Funcionario.h
Funcionario.cpp