PET FERA: Empresa Class Reference
Empresa Class Reference
#include "empresa.h"
Public Member Functions
Empresa ()
Empresa (string nome, string cnpj)
~Empresa ()
string getNome ()
void setNome (string nome)
string getCnpj ()
void setCnpj (string cnpj)
list< Funcionario > getFuncionarios ()
int getTotalFuncionarios ()
void setFuncionarios (list< Funcionario > funcionarios)
void inserirFuncionario (Funcionario funcionario)
Empresa & operator= (Empresa const &e)
Private Attributes
string nome
string cnpj
list< Funcionario > funcionarios
Friends
ostream & operator<< (ostream &o, Empresa const e)
Detailed Description
Definition at line 17 of file empresa.h.
Constructor & Destructor Documentation
Empresa() [1/2]
Empresa::Empresa ()
Definition at line 3 of file empresa.cpp.
References cnpj, funcionarios, and nome.
                 {
     this->nome = "";
     this->cnpj = "";
     this->funcionarios.empty();
 };
Empresa() [2/2]
Empresa::Empresa (string nome, string cnpj)
Definition at line 9 of file empresa.cpp.
References cnpj, funcionarios, and nome.
                                   : nome(n), cnpj(c){
     this->nome = n;
     this->cnpj = c;
     this->funcionarios.empty();
 };
~Empresa()
Empresa::~Empresa ()
Definition at line 27 of file empresa.cpp.
                  {
 };
Member Function Documentation
getCnpj()
string Empresa::getCnpj () inline
Definition at line 36 of file empresa.h.
Referenced by adicionarFuncionario(), aplicarAumento(), checarEmpresa(), listarFuncionarios(), and listarFuncionariosExperiencia().
                      {
         return this->cnpj;
     };
getFuncionarios()
list<Funcionario> Empresa::getFuncionarios () inline
Definition at line 42 of file empresa.h.
Referenced by aplicarAumento().
{
         return this->funcionarios;
     };
getNome()
string Empresa::getNome () inline
Definition at line 30 of file empresa.h.
Referenced by escolherEmpresa(), listarFuncionarios(), and listarFuncionariosExperiencia().
                      {
         return this->nome;
     };
getTotalFuncionarios()
int Empresa::getTotalFuncionarios () inline
Definition at line 46 of file empresa.h.
{
         return this->funcionarios.size();
     }
inserirFuncionario()
void Empresa::inserirFuncionario (Funcionario funcionario) inline
Definition at line 54 of file empresa.h.
References operator<<().
Referenced by adicionarFuncionario().
{
         this->funcionarios.push_back(funcionario);
     };
operator=()
Empresa & Empresa::operator= (Empresa const & e)
Definition at line 15 of file empresa.cpp.
References cnpj, funcionarios, and nome.
{
     this->nome = e.nome;
     this->cnpj = e.cnpj;
     this->funcionarios = e.funcionarios;
     return *this;
 }
setCnpj()
void Empresa::setCnpj (string cnpj) inline
Definition at line 39 of file empresa.h.
{
         this->cnpj = cnpj;
     };
setFuncionarios()
void Empresa::setFuncionarios (list< Funcionario > funcionarios) inline
Definition at line 50 of file empresa.h.
{
         this->funcionarios = funcionarios;
     }
setNome()
void Empresa::setNome (string nome) inline
Definition at line 33 of file empresa.h.
{
         this->nome = nome;
     };
Friends And Related Function Documentation
operator<<
ostream& operator<< (ostream & o, Empresa const e) friend
Definition at line 22 of file empresa.cpp.
{
     o << "nome: " << e.nome << " | cnpj : " << e.cnpj << endl;
     return o;
 }
Member Data Documentation
cnpj
string Empresa::cnpj private
Definition at line 21 of file empresa.h.
Referenced by Empresa(), operator<<(), and operator=().
funcionarios
list<Funcionario> Empresa::funcionarios private
Definition at line 22 of file empresa.h.
Referenced by Empresa(), and operator=().
nome
string Empresa::nome private
Definition at line 20 of file empresa.h.
Referenced by Empresa(), operator<<(), and operator=().
The documentation for this class was generated from the following files:
empresa.h
empresa.cpp