PET FERA: Animal Class Reference
Animal Class Reference
#include "Animal.h"
Public Member Functions
int getM_id ()
void setM_id (int m_id)
string getM_classe ()
void setM_classe (string m_classe)
string getM_nome ()
void setM_nome (string m_nome)
string getM_nome_cientifico ()
void setM_nome_cientifico (string m_nome_cientifico)
char getM_sexo ()
void setM_sexo (char m_sexo)
double getM_tamanho ()
void setM_tamanho (double m_tamanho)
string getM_dieta ()
void setM_dieta (string m_dieta)
string getM_nome_batismo ()
void setM_nome_batismo (string m_nome_batismo)
Veterinario getM_veterinario ()
void setM_veterinario (Veterinario m_veterinario)
Tratador getM_tratador ()
void setM_tratador (Tratador m_tratador)
Private Attributes
int m_id
string m_classe
string m_nome
string m_nome_cientifico
char m_sexo
double m_tamanho
string m_dieta
string m_nome_batismo
Tratador m_tratador
Veterinario m_veterinario
Friends
istream & operator>> (istream &is, Animal &animal)
Detailed Description
Definition at line 22 of file Animal.h.
Member Function Documentation
getM_classe()
string Animal::getM_classe ()
Definition at line 13 of file Animal.cpp.
References m_classe.
 {
     return this->m_classe;
 }
getM_dieta()
string Animal::getM_dieta ()
Definition at line 62 of file Animal.cpp.
References m_dieta.
 {
     return this->m_dieta;
 }
getM_id()
int Animal::getM_id ()
Definition at line 3 of file Animal.cpp.
References m_id.
 {
     return this->m_id;
 }
getM_nome()
string Animal::getM_nome ()
Definition at line 23 of file Animal.cpp.
References m_nome.
 {
     return this->m_nome;
 }
getM_nome_batismo()
string Animal::getM_nome_batismo ()
Definition at line 72 of file Animal.cpp.
References m_nome_batismo.
 {
     return this->m_nome_batismo;
 }
getM_nome_cientifico()
string Animal::getM_nome_cientifico ()
Definition at line 32 of file Animal.cpp.
References m_nome_cientifico.
 {
     return this->m_nome_cientifico;
 }
getM_sexo()
char Animal::getM_sexo ()
Definition at line 42 of file Animal.cpp.
References m_sexo.
 {
     return this->m_sexo;
 }
getM_tamanho()
double Animal::getM_tamanho ()
Definition at line 52 of file Animal.cpp.
References m_tamanho.
 {
     return this->m_tamanho;
 }
getM_tratador()
Tratador Animal::getM_tratador ()
Definition at line 91 of file Animal.cpp.
References m_tratador.
 {
     return this->m_tratador;
 }
getM_veterinario()
Veterinario Animal::getM_veterinario ()
Definition at line 81 of file Animal.cpp.
References m_veterinario.
 {
     return this->m_veterinario;
 }
setM_classe()
void Animal::setM_classe (string m_classe)
Definition at line 18 of file Animal.cpp.
References m_classe.
Referenced by SistemaAnimal::cadastrarAnimal().
 {
     this->m_classe = m_classe;
 }
setM_dieta()
void Animal::setM_dieta (string m_dieta)
Definition at line 67 of file Animal.cpp.
References m_dieta.
Referenced by SistemaAnimal::cadastrarAnimal().
 {
     this->m_dieta = m_dieta;
 }
setM_id()
void Animal::setM_id (int m_id)
Definition at line 8 of file Animal.cpp.
References m_id.
Referenced by SistemaAnimal::cadastrarAnimal(), and operator>>().
 {
     this->m_id = m_id;
 }
setM_nome()
void Animal::setM_nome (string m_nome)
Definition at line 28 of file Animal.cpp.
References m_nome.
Referenced by SistemaAnimal::cadastrarAnimal().
 {
     this->m_nome = m_nome;
 }
setM_nome_batismo()
void Animal::setM_nome_batismo (string m_nome_batismo)
Definition at line 77 of file Animal.cpp.
References m_nome_batismo.
Referenced by SistemaAnimal::cadastrarAnimal().
 {
     this->m_nome_batismo = m_nome_batismo;
 }
setM_nome_cientifico()
void Animal::setM_nome_cientifico (string m_nome_cientifico)
Definition at line 37 of file Animal.cpp.
References m_nome_cientifico.
Referenced by SistemaAnimal::cadastrarAnimal().
 {
     this->m_nome_cientifico = m_nome_cientifico;
 }
setM_sexo()
void Animal::setM_sexo (char m_sexo)
Definition at line 47 of file Animal.cpp.
References m_sexo.
Referenced by SistemaAnimal::cadastrarAnimal(), and operator>>().
 {
     this->m_sexo = m_sexo;
 }
setM_tamanho()
void Animal::setM_tamanho (double m_tamanho)
Definition at line 57 of file Animal.cpp.
References m_tamanho.
Referenced by SistemaAnimal::cadastrarAnimal(), and operator>>().
 {
     this->m_tamanho = m_tamanho;
 }
setM_tratador()
void Animal::setM_tratador (Tratador m_tratador)
Definition at line 96 of file Animal.cpp.
References m_tratador.
Referenced by SistemaAnimal::cadastrarAnimal().
 {
     this-> m_tratador = m_tratador;
 }
setM_veterinario()
void Animal::setM_veterinario (Veterinario m_veterinario)
Definition at line 86 of file Animal.cpp.
References m_veterinario.
Referenced by SistemaAnimal::cadastrarAnimal().
 {
     this->m_veterinario = m_veterinario;
 }
Friends And Related Function Documentation
operator>>
istream& operator>> (istream & is, Animal & animal) friend
Definition at line 102 of file Animal.cpp.
{
         /*string id;
   getline(is, id, ';');
         getline(is, animal.m_classe, ';');
         is>>animal.m_nome_cientifico;
         animal.setM_id(stoi(id));*/
         string id, tamanho, sexo;
   getline(is, id, ';');
         getline(is, animal.m_classe, ';');
         getline(is, animal.m_nome, ';');
         getline(is, animal.m_nome_cientifico, ';');
         getline(is, sexo, ';');
         animal.setM_sexo(sexo[0]);
         getline(is, tamanho, ';');
         getline(is, animal.m_dieta, ';');
         //getline(is, animal.m_nome_batismo,';');
         //getline(is, id_veterinario, ';');
         getline(is,animal.m_nome_batismo,';');
         try{
         if(!id.empty()) animal.setM_id(stoi(id));
         if(!tamanho.empty()) animal.setM_tamanho(stod(tamanho));
         }catch (const std::exception &e)
     {
       cout << "Id invlido ou existente" << endl;
     }
         /*is >> animal.m_id;
                 //>> delim
         is.ignore(2,';');
         is>> animal.m_classe;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_nome_cientifico;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_sexo;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_tamanho;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_dieta;
                 //>> delim
         //is.ignore(1,';');
         is>> animal.m_nome_batismo;*/
   return is;
 }
Member Data Documentation
m_classe
string Animal::m_classe private
Definition at line 26 of file Animal.h.
Referenced by getM_classe(), operator>>(), and setM_classe().
m_dieta
string Animal::m_dieta private
Definition at line 31 of file Animal.h.
Referenced by getM_dieta(), operator>>(), and setM_dieta().
m_id
int Animal::m_id private
Definition at line 25 of file Animal.h.
Referenced by getM_id(), and setM_id().
m_nome
string Animal::m_nome private
Definition at line 27 of file Animal.h.
Referenced by getM_nome(), operator>>(), and setM_nome().
m_nome_batismo
string Animal::m_nome_batismo private
Definition at line 32 of file Animal.h.
Referenced by getM_nome_batismo(), operator>>(), and setM_nome_batismo().
m_nome_cientifico
string Animal::m_nome_cientifico private
Definition at line 28 of file Animal.h.
Referenced by getM_nome_cientifico(), operator>>(), and setM_nome_cientifico().
m_sexo
char Animal::m_sexo private
Definition at line 29 of file Animal.h.
Referenced by getM_sexo(), and setM_sexo().
m_tamanho
double Animal::m_tamanho private
Definition at line 30 of file Animal.h.
Referenced by getM_tamanho(), and setM_tamanho().
m_tratador
Tratador Animal::m_tratador private
Definition at line 33 of file Animal.h.
Referenced by getM_tratador(), and setM_tratador().
m_veterinario
Veterinario Animal::m_veterinario private
Definition at line 34 of file Animal.h.
Referenced by getM_veterinario(), and setM_veterinario().
The documentation for this class was generated from the following files:
Animal.h
Animal.cpp