PET FERA: dataUtil.h File Reference
dataUtil.h File Reference
Utilitário de Data.
#include <ctime>
#include <iostream>
#include <sstream>
#include <iomanip>
#include <regex>
#include "stringUtil.h"
#include "../modelos/data/data.h"
Functions
string dateToString (Data data)
converte uma data para string
Data stringToData (string dataString)
converte string para data
bool checarFormatoData (string dataString)
checa se uma string está no formato dd/mm/yyyy
bool checarDataValida (Data data)
checa se uma data é valida
double diferencaDatas (Data data, tm *dataAtual)
retorna a diferença entre uma data e a data atual
tm * getTimeNow ()
retorna a data atual
Detailed Description
Utilitário de Data.
Author
Felipe Rodrigues
Since
23/04/2019
Date
01/05/2019
Definition in file dataUtil.h.
Function Documentation
checarDataValida()
bool checarDataValida (Data data)
checa se uma data é valida
Parameters
objeto do tipo data
Returns
1 se verdadeiro, 0 se falso
Definition at line 53 of file dataUtil.cpp.
References Data::getAno(), Data::getDia(), Data::getMes(), and getTimeNow().
{
     if(data.getDia() <= 31 && data.getDia() >= 1){
         if(data.getMes() <= 12 && data.getMes() >= 1){
             if(data.getAno() <= getTimeNow()->tm_year+1900){
                 return true;
             }
             return false;
         }
         return false;
     }
     return false;
 }
checarFormatoData()
bool checarFormatoData (string dataString)
checa se uma string está no formato dd/mm/yyyy
Parameters
string a ser convertida
Returns
1 se verdadeiro, 0 se falso
Definition at line 33 of file dataUtil.cpp.
Referenced by stringToData().
{
     struct tm tm;
     if (strptime(dataString.c_str(), "%d/%m/%Y", &tm))
         return true;
     return false;
 }
dateToString()
string dateToString (Data data)
converte uma data para string
Parameters
data a ser convertida
Returns
string no formato dd/mm/yyyy
Definition at line 8 of file dataUtil.cpp.
References Data::getAno(), Data::getDia(), and Data::getMes().
{
     string dateString;
     dateString = to_string(data.getDia()) + "/" + to_string(data.getMes()) + "/" + to_string(data.getAno());
     return dateString;
 }
diferencaDatas()
double diferencaDatas (Data data, tm * dataAtual)
retorna a diferença entre uma data e a data atual
Parameters
objeto do tipo data, ponteiro da data atual
Returns
valor da diferença entre as data
Definition at line 70 of file dataUtil.cpp.
References Data::getAno(), Data::getDia(), and Data::getMes().
{
     double anoAtual = dataAtual->tm_year + 1900;
     double valorData = data.getDia() + (data.getMes()* 30) + (data.getAno() * 365);
     double valorDataAtual = dataAtual->tm_mday + (dataAtual->tm_mon* 30) +  (anoAtual* 365);
     // cout << dataAtual->tm_mday <<"-" << dataAtual->tm_mon <<"-"<<anoAtual << endl;
     // cout << data.getDia() <<"-" << data.getMes() <<"-"<<data.getAno() << endl;
     // cout << valorDataAtual<<"-" << valorData << endl;
     // cout <<  valorDataAtual - valorData;
     return valorDataAtual - valorData;
 }
getTimeNow()
tm* getTimeNow ()
retorna a data atual
Returns
ponteiro do tipo tm
Definition at line 43 of file dataUtil.cpp.
Referenced by checarDataValida().
                 {
     time_t t = time(NULL);
         tm* timePtr = localtime(&t);
     return timePtr;
 }
stringToData()
Data stringToData (string dataString)
converte string para data
Parameters
string a ser convertida
Returns
objeto do tipo Data
Definition at line 18 of file dataUtil.cpp.
References checarFormatoData(), and splitString().
{
     if (checarFormatoData(dataString)) {
         vector<string> dataSplitted = splitString(dataString, "/");
         Data data = Data(stoi(dataSplitted[0]), stoi(dataSplitted[1]),stoi(dataSplitted[2]));
         return data;
     }else {
         return Data();
     }
 }