PET FERA: empresa-crud.cpp File Reference
empresa-crud.cpp File Reference
#include "empresa-crud.h"
Functions
Empresa criarEmpresa ()
Cria uma empresa.
void adicionarFuncionario (list< Empresa > *empresas, Funcionario *funcionario)
Adiciona um funcionario à uma empresa já existente.
void listarFuncionarios (list< Empresa > empresas)
Lista todos os funcionários de uma empresa.
void listarFuncionariosExperiencia (list< Empresa > empresas)
Lista funcionários contratados em até 90 dias.
void listarMediaFuncionarios (list< Empresa > empresas)
Lista a quantidade de funcionarios por empresa e a média.
void aplicarAumento (list< Empresa > *empresas)
Aplica aumento a todos os funcionarios de uma empresa.
Empresa escolherEmpresa (list< Empresa > empresas)
Telas para escolha de empresas.
Function Documentation
adicionarFuncionario()
void adicionarFuncionario (list< Empresa > * empresas, Funcionario * funcionario)
Adiciona um funcionario à uma empresa já existente.
Parameters
Ponteiro da lista de empresas e ponteiro do funcionário a ser adicionado
Definition at line 30 of file empresa-crud.cpp.
References escolherEmpresa(), Empresa::getCnpj(), Empresa::inserirFuncionario(), and Funcionario::setNomeEmpresa().
Referenced by iniciarMenu().
{
     Empresa empresaEscolhida = escolherEmpresa(*empresas);
     empresaEscolhida.inserirFuncionario(*funcionario);
     for (auto &empresa : *empresas) {
         if(empresa.getCnpj() == empresaEscolhida.getCnpj()){
             funcionario->setNomeEmpresa(empresa.getNome());
             empresa.inserirFuncionario(*funcionario);
         }
     }
 }
aplicarAumento()
void aplicarAumento (list< Empresa > * empresas)
Aplica aumento a todos os funcionarios de uma empresa.
Parameters
Ponteiro da lista de empresas
Definition at line 109 of file empresa-crud.cpp.
References CYAN, escolherEmpresa(), Empresa::getCnpj(), Empresa::getFuncionarios(), isDouble(), RED, and RESET.
Referenced by iniciarMenu().
{
     string entrada;
     double coeficiente = 0.0;
     cout <<CYAN<<"--- APLICAR AUMENTO ---"<<RESET<< endl;
     cout << "valor(%): ";
     cin >> entrada;
     if(isDouble(entrada)){
         coeficiente = stod(entrada) / 100;
         Empresa empresaEscolhida = escolherEmpresa(*empresas);
         list<Funcionario> funcionarios = empresaEscolhida.getFuncionarios();
         for (auto &funcionario : funcionarios) {
             double aumento = funcionario.getSalario() * coeficiente;
             funcionario.setSalario(funcionario.getSalario() + aumento);
         }
         //atualiza a lista de funcionarios agora com o aumento
         for (auto &empresa: *empresas){
             if(empresa.getCnpj() == empresaEscolhida.getCnpj()){
                 empresa.setFuncionarios(funcionarios);
             }
         }
     } else {
         cout << RED << "Valor inválido!" << RESET << endl;
         throw std::exception();
     }
 }
criarEmpresa()
Empresa criarEmpresa ()
Cria uma empresa.
Returns
Empresa criada
Definition at line 6 of file empresa-crud.cpp.
References CYAN, isEmpty(), RESET, and YELLOW.
Referenced by iniciarMenu().
                       {
     string nome, cnpj;
     Empresa empresa;
     bool inputVazio;
     do {
         inputVazio = false;
         cout <<CYAN<<"--- CRIAR EMPRESA ---"<<RESET<< endl;
         cout << "- nome: ";
         cin.ignore();
         getline(cin, nome);
         cout << "- cnpj: ";
         getline(cin, cnpj);
         if(isEmpty(nome) || isEmpty(cnpj)) {
             inputVazio = true;
             cout << YELLOW << "Nome ou CNPJ vazios!" << RESET << endl;
         }
     } while(inputVazio);
     empresa = Empresa(nome, cnpj);
     return empresa;
 }
escolherEmpresa()
Empresa escolherEmpresa (list< Empresa > empresas)
Telas para escolha de empresas.
Parameters
Lista de empresas
Returns
Empresa escolhida
Definition at line 142 of file empresa-crud.cpp.
References CYAN, Empresa::getNome(), RESET, and YELLOW.
Referenced by adicionarFuncionario(), aplicarAumento(), listarFuncionarios(), and listarFuncionariosExperiencia().
{
     string continuar;
     Empresa empresaEscolhida;
     string escolha;
     do {
         cout << CYAN<< "--- SELECIONE A EMPRESA ---"<<RESET<< endl;
         if(empresas.size() == 0){
             cout << YELLOW << "Nenhuma empresa cadastrada!" << RESET << endl;
             continuar = "N";
         } else {
             for (auto & empresa : empresas) {
                 cout << empresa;
             }
             cout << "empresa (cnpj): ";
             cin.ignore();
             getline(cin, escolha);
             for (auto & empresa : empresas) {
                 if(empresa.getCnpj() == escolha){
                     empresaEscolhida = empresa;
                 }
             }
             if(!empresaEscolhida.getNome().size()){
                 cout << "Empresa inválida! Deseja continuar? (S/N)" << endl;
                 cin >> continuar;
             }
         }
     } while(continuar == "S" && !empresaEscolhida.getNome().size());
     return empresaEscolhida;
 }
listarFuncionarios()
void listarFuncionarios (list< Empresa > empresas)
Lista todos os funcionários de uma empresa.
Parameters
Lista de empresas
Definition at line 44 of file empresa-crud.cpp.
References escolherEmpresa(), Empresa::getCnpj(), Empresa::getNome(), GREEN, RESET, and YELLOW.
Referenced by iniciarMenu().
{
     Empresa empresaEscolhida = escolherEmpresa(empresas);
     for (auto empresa : empresas) {
         if(empresa.getCnpj() == empresaEscolhida.getCnpj()){
             if (empresa.getTotalFuncionarios() > 0) {
                 cout << GREEN << "--- FUNCIONÁRIOS DE " <<(empresaEscolhida.getNome())<<" ---"<<RESET<<endl;
                 for (auto &funcionario : empresa.getFuncionarios()) {
                     cout << funcionario;
                 }
             } else {
                 cout << YELLOW << "Nenhum funcionário cadastrado!" << RESET << endl;
             }
         }
     }
 }
listarFuncionariosExperiencia()
void listarFuncionariosExperiencia (list< Empresa > empresas)
Lista funcionários contratados em até 90 dias.
Parameters
Lista de empresas
Definition at line 63 of file empresa-crud.cpp.
References checarExperiencia(), escolherEmpresa(), Empresa::getCnpj(), Empresa::getNome(), GREEN, RESET, and YELLOW.
Referenced by iniciarMenu().
{
     int countExp = 0;
     Empresa empresaEscolhida = escolherEmpresa(empresas);
     for (auto empresa : empresas) {
         if(empresa.getCnpj() == empresaEscolhida.getCnpj()){
             if (empresa.getTotalFuncionarios() > 0) {
                 cout << GREEN << "funcionários em treinamento de " <<(empresaEscolhida.getNome()) <<RESET<<endl;
                 for (auto &funcionario : empresa.getFuncionarios()) {
                     if (checarExperiencia(funcionario)){
                         cout << funcionario;
                         countExp++;
                     }
                 }
                 if(countExp == 0) {
                      cout << YELLOW << "Nenhum funcionário em periodo de experiência!" << RESET << endl;
                 }
             } else {
                 cout << YELLOW << "Nenhum funcionário cadastrado!" << RESET << endl;
             }
         }
     }
 }
listarMediaFuncionarios()
void listarMediaFuncionarios (list< Empresa > empresas)
Lista a quantidade de funcionarios por empresa e a média.
Parameters
Lista de empresas
Definition at line 90 of file empresa-crud.cpp.
References CYAN, GREEN, and RESET.
Referenced by iniciarMenu().
{
     int contador = 0;
     double media = 0.0;
     double somatorio = 0.0;
     cout << CYAN << "--- MÉDIA ---" << RESET << endl;
     for (auto empresa : empresas) {
         cout << GREEN<<empresa.getNome() << " : " << empresa.getTotalFuncionarios() << endl;
         somatorio += empresa.getTotalFuncionarios();
         contador++;
     }
     media = somatorio / contador;
     cout << "=========" << endl;
     cout << "média: " << media << RESET << endl;
 }