PET FERA: funcionario-crud.cpp File Reference
funcionario-crud.cpp File Reference
#include "funcionario-crud.h"
Functions
Funcionario criarFuncionario ()
Cria um funcionario.
bool checarExperiencia (Funcionario funcionario)
Checa se um funcionario é inexperiente.
Function Documentation
checarExperiencia()
bool checarExperiencia (Funcionario funcionario)
Checa se um funcionario é inexperiente.
Parameters
Funcionario a ser checado
Returns
1 se inexperiente, 0 se não;
Definition at line 55 of file funcionario-crud.cpp.
References diferencaDatas(), Funcionario::getDataAdmissao(), and getTimeNow().
Referenced by listarFuncionariosExperiencia().
{
    return diferencaDatas(funcionario.getDataAdmissao(), getTimeNow()) <= 90 ? true : false;
 }
criarFuncionario()
Funcionario criarFuncionario ()
Cria um funcionario.
Returns
Funcionario criado
Definition at line 15 of file funcionario-crud.cpp.
References checarDataValida(), CYAN, isDouble(), isEmpty(), RED, RESET, stringToData(), and YELLOW.
Referenced by iniciarMenu().
{
     string nome, inputDate, salario;
     Data dataAdmissao;
     Funcionario funcionario;
     bool invalidInput;
     do {
         invalidInput = false;
         cout << CYAN<<"--- FUNCIONÁRIO ---"<<RESET<< endl;
         cout << "- nome: ";
         cin.ignore();
         getline(cin, nome);
         cout << "- salário: ";
         getline(cin, salario);
         if(isDouble(salario)){
             cout << "- data de admissão (dd/mm/yyyy): ";
             cin >> inputDate;
             dataAdmissao = stringToData(inputDate);
             if(checarDataValida(dataAdmissao)){
                  funcionario = Funcionario(nome, stod(salario), dataAdmissao);
             } else {
                 cout << RED << "Data inválida!" << RESET << endl;
                 invalidInput = true;
             }
         } else {
             cout << RED << "Salário inválido!" << RESET << endl;
             invalidInput = true;
         }
         if(isEmpty(nome)){
             invalidInput = true;
             cout << YELLOW << "Nenhum campo pode ser vazio!" << RESET << endl;
         }
     }while(invalidInput);
     return funcionario;
 }