PET FERA: menu-principal.cpp File Reference
menu-principal.cpp File Reference
Implementação do menu do sistema.
#include "menu-principal.h"
Functions
void iniciarMenu ()
inicializa o menu do sistema
int escolherOpcao ()
carrega o menu de opções
void mensagemSucesso (string mensagem)
checa se uma empresa já existe
void mensagemErro (string mensagem)
exibe mensagem de erro na tela
Detailed Description
Implementação do menu do sistema.
Author
Felipe Rodrigues
Definition in file menu-principal.cpp.
Function Documentation
escolherOpcao()
int escolherOpcao ()
carrega o menu de opções
Returns
valor referente a opção escolhida
Definition at line 50 of file menu-principal.cpp.
References CYAN, isInt(), RED, and RESET.
Referenced by iniciarMenu().
                    {
     set<int> options = {0,1,2,3,4,5,6,7,8};
     string op;
     cout <<CYAN<< "--- MENU PRINCIPAL ---"<<RESET<< endl;
     cout << "1 - criar funcionário" << endl;
     cout << "2 - editar funcionário" << endl;
     cout << "3 - deletar funcionario" << endl;
     cout << "4 - listar funcionarios" << endl;
     cout << "5 - criar animal" << endl;
     cout << "6 - editar animal" << endl;
     cout << "7 - deletar animal" << endl;
     cout << "8 - listar animais" << endl;
     cout << "0 - sair"<<endl;
     cin >> op;
     if(isInt(op)){
         const bool opValida = options.find(stoi(op)) != options.end();
         if(opValida){
             return stoi(op);
         }
     }
     cout << RED << "Opção inválida!" << RESET<< endl;
     return -1;
 }
iniciarMenu()
void iniciarMenu ()
inicializa o menu do sistema
Definition at line 11 of file menu-principal.cpp.
References Sistema::alterar_Funcionario(), Sistema::cadastrar_Funcionario(), escolherOpcao(), Sistema::mostrar_Funcionarios(), and Sistema::remover_Funcionario().
                   {
     int option;
     cout << "Bem vindo!" << endl;
     do{
         option = escolherOpcao();
         switch(option){
             case 1: {
                 Sistema *s = new Sistema();
                 s->cadastrar_Funcionario();
                 delete(s);
                 break;
             }
             case 2: {
                  Sistema *s = new Sistema();
                  s->alterar_Funcionario();
                  delete(s);
                  break;
             }
             case 3:{
                  Sistema *s = new Sistema();
                  s->remover_Funcionario();
                  delete(s);
                  break;
             }
             case 4:{
                  Sistema *s = new Sistema();
                  s->mostrar_Funcionarios();
                  delete(s);
                  break;
             }
             default:
                 break;
         }
     }while(option != 0);
 }
mensagemErro()
void mensagemErro (string mensagem)
exibe mensagem de erro na tela
Parameters
mensagem a ser exibida
Definition at line 116 of file menu-principal.cpp.
References RED, and RESET.
{
     cout << RED << mensagem << RESET << endl;
 }
mensagemSucesso()
void mensagemSucesso (string mensagem)
checa se uma empresa já existe
Parameters
lista de empresas já cadastradas, empresa a ser checada
Returns
1 se já existe, 0 se não existe checa se um funcionario já existe
Parameters
lista de empresas já cadastradas, funcionario a ser checado
Returns
1 se já existe, 0 se não existe : checar por empresa exibe mensagem de sucesso na tela
Parameters
mensagem a ser exibida
Definition at line 109 of file menu-principal.cpp.
References GREEN, and RESET.
{
     cout << GREEN << mensagem << RESET << endl;
 }